

parameters:
- name: platform
  type: string
  default: linux

steps:

- ${{ if eq(parameters.platform, 'linux') }}:
  - script: |
      # Fetch the latest Bicep CLI binary
      curl -Lo bicep.bin https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
      # Mark it as executable
      chmod +x ./bicep.bin
      # Add bicep to your PATH (requires admin)
      sudo mv ./bicep.bin /usr/local/bin/bicep
    displayName: 'Install Bicep'

- ${{ if eq(parameters.platform, 'macos') }}:
  - script: |
      # Fetch the latest Bicep CLI binary
      curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-osx-x64
      # Mark it as executable
      chmod +x ./bicep
      # Add Gatekeeper exception (requires admin)
      sudo spctl --add ./bicep
      # Add bicep to your PATH (requires admin)
      sudo mv ./bicep /usr/local/bin/bicep
    displayName: 'Install Bicep'

- ${{ if eq(parameters.platform, 'windows') }}:
  - script: |
      # Create the install folder
      $installPath = "$env:USERPROFILE\.bicep"
      $installDir = New-Item -ItemType Directory -Path $installPath -Force
      $installDir.Attributes += 'Hidden'
      # Fetch the latest Bicep CLI binary
      (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
      # Add bicep to your PATH
      $currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
      if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
      if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
    displayName: 'Install Bicep'
