# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

site_name: PSRule for Azure
site_url: https://azure.github.io/PSRule.Rules.Azure
site_description: Ready to go rules for testing Azure Infrastructure as Code (IaC).
site_author: Microsoft

repo_url: https://github.com/Azure/PSRule.Rules.Azure/
edit_uri: blob/main/docs/

repo_issue: https://github.com/Azure/PSRule.Rules.Azure/issues
repo_discussion: https://github.com/Azure/PSRule.Rules.Azure/discussions

extra_css:
- assets/stylesheets/extra.css

theme:
  language: en
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  palette:
    primary: black
    accent: blue
  logo: assets/ms_icon.png
  favicon: assets/ms_icon.png
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.indexes
  - navigation.sections:
      level: 1
  - navigation.tabs
  - navigation.footer
  - content.code.annotate
  - content.tabs.link
  - content.code.copy
  - content.action.edit
  - content.action.view

nav:
  - Home: index.md
  - Getting started:
    - Overview:
      - About: about.md
      - Features: features.md
      - FAQ: faq.md
    - Install: install.md
    - Quickstarts:
      - Test a Bicep deployment:
        - With GitHub Actions: quickstarts/test-bicep-with-github.md
        - With Azure Pipelines: quickstarts/test-bicep-with-azure-pipelines.md
        # - With Visual Studio Code: quickstarts/test-bicep-with-vscode.md
    # - Tutorials:
    - Testing infrastructure code:
      - Expanding source files: expanding-source-files.md
      - Using templates: using-templates.md
      - Using Bicep source: using-bicep.md
      - Creating your pipeline: creating-your-pipeline.md
    - Testing deployed resources:
      - Exporting rule data: export-rule-data.md
      - Analyzing resources: analyzing-resources.md
    - Concepts:
      - Working with baselines: working-with-baselines.md
      - Suppression: concepts/suppression.md
      - Policy as rules: concepts/policy-as-rules.md
    - Customization:
      - Using custom rules: customization/using-custom-rules.md
      - Enforcing custom tags: customization/enforce-custom-tags.md
      - Enforcing code ownership: customization/enforce-codeowners.md
      - Permit outbound management: customization/permit-outbound-management.md
    - Troubleshooting: troubleshooting.md
    - Samples: samples.md
    - License:
      - license-contributing/index.md
    - Related projects: related-projects.md
    - Support: support.md
  - Updates:
    - Change log: changelog.md
    - Upgrade notes: upgrade-notes.md
    - Deprecations: deprecations.md
    - Changes and versioning: versioning.md
  - Setup:
    - Configuring options:
      - setup/index.md
      - Configuring rule defaults: setup/configuring-rules.md
      - Configuring expansion: setup/configuring-expansion.md
      - Configuring exports: setup/configuring-exports.md
    - Setup Bicep: setup/setup-bicep.md
    - Setup Azure Monitor logs: setup/setup-azure-monitor-logs.md
    - Setup naming and tagging: setup/setup-naming-and-tagging.md
    - Integrations: integrations.md
  - Reference:
    - en/rules/index.md
    - By pillar: en/rules/module.md
    - By resource: en/rules/resource.md
    - Microsoft Cloud Security Benchmark: en/mcsb-v1.md
  - Contribute:
    - Overview: contribute/overview.md
    - Rules:
      - 1. Complete prerequisites: contribute/rules/prerequisites.md
      - 2. Create or assign an issue: contribute/rules/create-issue.md
      - 3. Choosing identifiers: contribute/rules/identifiers.md
      - 4. Create or update a rule: contribute/rules/create-rule.md
      - 5. Testing a rule: contribute/rules/testing.md
      - 6. Adding rule help: contribute/rules/help.md
      - 7. Update the change log: contribute/rules/change-log.md
      - 8. Submit a pull request: contribute/rules/pull-request.md
    - Writing documentation: license-contributing/writing-documentation.md
    - Resources:
      - Metadata reference: license-contributing/metadata-reference.md
      - Expansion internals: license-contributing/expansion-internals.md
      - Get started contributing: license-contributing/get-started-contributing.md
      - Getting started with contributions: license-contributing/getting-started-with-documentation.md
    - Contribution Q&A: contribute/contribution-qna.md
    - Past hackathons: license-contributing/hackathons.md
  - Learn:
    - Learn PSRule for Azure series: learn/learn-video-series.md
    - Official learning: learn/official.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/en/abbreviations.md
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - mdx_truly_sane_lists
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: '#'
      separator: '-'

plugins:
- git-revision-date-localized:
    enable_creation_date: true
    fallback_to_build_date: true
- git-committers:
    enabled: !ENV [GITHUB_ACTIONS, false]
    repository: Azure/PSRule.Rules.Azure
    branch: main
- search
- tags:
    tags: false
- redirects:
    redirect_maps:
      install-instructions.md: install.md
      validating-locally.md: install.md
      using-metadata.md: using-templates.md
      customization/index.md: customization/using-custom-rules.md
      customization/storing-custom-rules.md: customization/using-custom-rules.md
      en/asb-v3.md: en/mcsb-v1.md
      setup/configuring-options.md: setup/index.md
      CHANGELOG-v1.md: changelog.md
      CHANGELOG-v0.md: https://github.com/Azure/PSRule.Rules.Azure/blob/v0.19.0/CHANGELOG.md

hooks:
  - docs/hooks/samples.py
  - docs/hooks/updates.py
  - docs/hooks/shortcodes.py
  - docs/hooks/metadata.py
  - docs/hooks/aliases.py
  - docs/hooks/old_hooks.py

watch:
  - includes

exclude_docs: |
  specs/
  benchmark/
  examples/
  *.bicep
  examples.json

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Azure/PSRule.Rules.Azure/

  local:
    social_preview: https://repository-images.githubusercontent.com/184154668/58818c00-d496-11eb-9b77-016145022654

  giscus:
    repo: Azure/PSRule.Rules.Azure
    repo_id: MDEwOlJlcG9zaXRvcnkxODQxNTQ2Njg=
    category: Documentation
    category_id: DIC_kwDOCvn6LM4CQqE6

  # alternate:
  #   - name: English
  #     link: /PSRule.Rules.Azure/en/
  #     lang: en
  #   - name: Spanish
  #     link: /PSRule.Rules.Azure/es/
  #     lang: es
