# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

site_name: PSRule for Azure
site_url: https://azure.github.io/PSRule.Rules.Azure
site_description: Ready to go rules for testing Azure Infrastructure as Code (IaC).
site_author: Microsoft

repo_url: https://github.com/Azure/PSRule.Rules.Azure/
edit_uri: blob/main/docs/

repo_issue: https://github.com/Azure/PSRule.Rules.Azure/issues
repo_discussion: https://github.com/Azure/PSRule.Rules.Azure/discussions

extra_css:
- assets/stylesheets/extra.css

theme:
  language: en
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  palette:
    primary: black
    accent: blue
  logo: assets/ms_icon.png
  favicon: assets/ms_icon.png
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.indexes
  - navigation.sections:
      level: 1
  - navigation.tabs
  - content.code.annotate
  - content.tabs.link
  - content.code.copy

nav:
  - Home: index.md
  - Getting started:
    - Overview:
      - About: about.md
      - Features: features.md
      - FAQ: faq.md
    - Install: install.md
    - Testing infrastructure code:
      - Expanding source files: expanding-source-files.md
      - Using templates: using-templates.md
      - Using Bicep source: using-bicep.md
      - Creating your pipeline: creating-your-pipeline.md
      - Working with baselines: working-with-baselines.md
    - Testing deployed resources:
      - Exporting rule data: export-rule-data.md
      - Analyzing resources: analyzing-resources.md
    - Concepts:
      - Suppression: concepts/suppression.md
    - Customization:
      - Storing custom rules: customization/storing-custom-rules.md
      - Enforcing custom tags: customization/enforce-custom-tags.md
      - Enforcing code ownership: customization/enforce-codeowners.md
      - Permit outbound management: customization/permit-outbound-management.md
    - Troubleshooting: troubleshooting.md
    - Samples: samples.md
    - License and contributing:
      - Index: license-contributing/index.md
      - Writing documentation: license-contributing/writing-documentation.md
      - Past hackathons: license-contributing/hackathons.md
    - Related projects: related-projects.md
    - Releases:
      - Change log:
        - v1: 'CHANGELOG-v1.md'
        - v0: 'CHANGELOG-v0.md'
      - Upgrade notes: upgrade-notes.md
      - Deprecations: deprecations.md
      - Changes and versioning: versioning.md
    - Support: support.md
  - Setup:
    - Configuring options: setup/configuring-options.md
    - Configuring rule defaults: setup/configuring-rules.md
    - Configuring expansion: setup/configuring-expansion.md
    - Setup Bicep: setup/setup-bicep.md
    - Setup Azure Monitor logs: setup/setup-azure-monitor-logs.md
    - Integrations: integrations.md
  - Reference:
    - Index: en/rules/index.md
    - By pillar: en/rules/module.md
    - By resource: en/rules/resource.md
    - Microsoft Cloud Security Benchmark: en/mcsb-v1.md
  - Learn:
    - Learn PSRule for Azure series: learn/learn-video-series.md
    - Official learning: learn/official.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: false
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - mdx_truly_sane_lists
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: '#'
      separator: '-'

plugins:
- mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs.hooks:replace_maml"
      on_nav: "docs.hooks:build_reference_nav"
- search
- git-revision-date
- tags
- redirects:
    redirect_maps:
      install-instructions.md: install.md
      validating-locally.md: install.md
      using-metadata.md: using-templates.md
      customization/index.md: customization/storing-custom-rules.md
      en/asb-v3.md: en/mcsb-v1.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Azure/PSRule.Rules.Azure/

  local:
    social_preview: https://repository-images.githubusercontent.com/184154668/58818c00-d496-11eb-9b77-016145022654

  giscus:
    repo: Azure/PSRule.Rules.Azure
    repo_id: MDEwOlJlcG9zaXRvcnkxODQxNTQ2Njg=
    category: Documentation
    category_id: DIC_kwDOCvn6LM4CQqE6

  # alternate:
  #   - name: English
  #     link: /PSRule.Rules.Azure/en/
  #     lang: en
  #   - name: Spanish
  #     link: /PSRule.Rules.Azure/es/
  #     lang: es
