# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# Rules for App Configuration
#

#region Rules

---
# Synopsis: App Configuration should use a minimum size of Standard.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppConfig.SKU
  ref: AZR-000057
  tags:
    release: GA
    ruleSet: 2020_12
    Azure.WAF/pillar: Reliability
spec:
  type:
  - Microsoft.AppConfiguration/configurationStores
  condition:
    field: 'Sku.Name'
    equals: 'standard'

---
# Synopsis: App Configuration store names should meet naming requirements.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppConfig.Name
  ref: AZR-000058
  tags:
    release: GA
    ruleSet: 2020_12
    Azure.WAF/pillar: Operational Excellence
  labels:
    Azure.CAF: naming
spec:
  type:
  - Microsoft.AppConfiguration/configurationStores
  condition:
    allOf:
    - name: '.'
      greaterOrEquals: 5
    - name: '.'
      lessOrEquals: 50
    # Alphanumerics and hyphens
    # Start and end with alphanumeric
    - name: '.'
      match: '^[A-Za-z0-9](-|[A-Za-z0-9]){3,48}[A-Za-z0-9]$'

---
# Synopsis: Use identity-based authentication for App Configuration.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.AppConfig.DisableLocalAuth
  ref: AZR-000291
  tags:
    release: GA
    ruleSet: 2022_09
    Azure.WAF/pillar: Security
  labels:
    Azure.MCSB.v1/control: 'IM-1'
    Azure.WAF/maturity: 'L1'
spec:
  type:
  - Microsoft.AppConfiguration/configurationStores
  condition:
    field: properties.disableLocalAuth
    equals: true

#endregion Rules
