#
# Automated dependency updates
#

# NOTES:
# This automatically bumps PowerShell dependency versions.

name: Dependencies
on:
  schedule:
    - cron:  '30 1 * * 1' # At 01:30 AM, on Monday each week
  workflow_dispatch:

env:
  WORKING_BRANCH: dependencies/powershell-bump

jobs:
  dependencies:
    name: Bump dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Configure
        run: |
          git config user.name github-actions
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Get working branch
        run: |
          git checkout -b ${{ env.WORKING_BRANCH }}

      - name: Check dependencies
        run: |
          ./scripts/dependencies.ps1
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
